version: '3.9'
services:
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db


  api:
    build: .
    ports:
      - 4000:3000
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongo_db:27017
      DB_NAME: my_db
      DB_USER: samim
    depends_on:
      - mongo_db
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules  

volumes: 
 mongo_db: {}
